<?php
$noaaradar_stations_list = array(
'Alabama' => array(
  'bmx' => 'Birmingham',
  'mxx' => 'E. Alabama',
  'eox' => 'Fort Rucker',
  'mob' => 'Mobile',
  'htx' => 'Nrn. Alabama'
  ),
'Alaska' => array(
  'abc' => 'Bethel',
  'acg' => 'Biorka Is.',
  'apd' => 'Fairbanks',
  'ahg' => 'Kenai',
  'akc' => 'King Salmon',
  'aih' => 'Middleton Is.',
  'aec' => 'Nome',
  'apd' => 'Pedro Dome',
  'acg' => 'Sitka'
  ),
'Arizona' => array(
  'fsx' => 'Flagstaff',
  'iwa' => 'Phoenix',
  'emx' => 'Tucson',
  'yux' => 'Yuma'
  ),
'Arkansas' => array(
  'lzk' => 'Little Rock',
  'srx' => 'W. Ark./Ft. Smith'
  ),
'California' => array(
  'bbx' => 'Beale AFB',
  'eyx' => 'Edwards AFB',
  'bhx' => 'Eureka',
  'hnx' => 'Hanford',
  'vtx' => 'Los Angeles',
  'dax' => 'Sacramento',
  'nkx' => 'San Diego',
  'mux' => 'San Francisco',
  'hnx' => 'San Joaquin Vly.',
  'sox' => 'Santa Ana Mtns',
  'vbx' => 'Vandenberg AFB'
  ),
'Colorado' => array(
  'ftg' => 'Denver/Boulder',
  'gjx' => 'Grand Junction',
  'pux' => 'Pueblo'
  ),
'Delaware' => array(
  'dox' => 'Dover AFB'
  ),
'Florida' => array(
  'evx' => 'Eglin AFB',
  'jax' => 'Jacksonville',
  'byx' => 'Key West',
  'mlb' => 'Melbourne',
  'amx' => 'Miami',
  'evx' => 'NW Florida',
  'tlh' => 'Tallahassee',
  'tbw' => 'Tampa Bay Area'
  ),
'Georgia' => array(
  'ffc' => 'Atlanta',
  'vax' => 'Moody AFB',
  'ffc' => 'Peachtree City',
  'jgx' => 'Robins AFB'
  ),
'Guam' => array(
  'gua' => 'Andersen AFB'
  ),
'Hawaii' => array(
  'hki' => 'Kauai',
  'hkm' => 'Kohala',
  'hmo' => 'Molokai',
  'hwa' => 'South Shore'
  ),
'Idaho' => array(
  'cbx' => 'Boise',
  'sfx' => 'Pocatello'
  ),
'Illinois' => array(
  'ilx' => 'Central IL',
  'lot' => 'Chicago'
  ),
'Indiana' => array(
  'vwx' => 'Evansville',
  'ind' => 'Indianapolis',
  'iwx' => 'Nrn. Indiana'
  ),
'Iowa' => array(
  'dmx' => 'Des Moines',
  'dvn' => 'Quad Cities'
  ),
'Kansas' => array(
  'ddc' => 'Dodge City',
  'gld' => 'Goodland',
  'twx' => 'Topeka',
  'ict' => 'Wichita'
  ),
'Kentucky' => array(
  'hpx' => 'Fort Cambell',
  'jkl' => 'Jackson',
  'lvx' => 'Louisville',
  'pah' => 'Paducah'
  ),
'Louisiana' => array(
  'poe' => 'Fort Polk',
  'lch' => 'Lake Charles',
  'lix' => 'New Orleans',
  'shv' => 'Shreveport'
  ),
'Maine' => array(
  'cbw' => 'Caribou',
  'gyx' => 'Portland'
  ),
'Maryland' => array(
  'lwx' => 'Baltimore'
  ),
'Massachusetts' => array(
  'box' => 'Boston'
  ),
'Michigan' => array(
  'dtx' => 'Detroit',
  'apx' => 'Gaylord',
  'grr' => 'Grand Rapids',
  'mqt' => 'Marquette'
  ),
'Minnesota' => array(
  'dlh' => 'Duluth',
  'mpx' => 'Minneapolis'
  ),
'Mississippi' => array(
  'gwx' => 'Columbus AFB',
  'dgx' => 'Jackson/Brandon'
  ),
'Missouri' => array(
  'eax' => 'Kansas City',
  'sgf' => 'Springfield',
  'lsx' => 'St. Louis'
  ),
'Montana' => array(
  'blx' => 'Billings',
  'ggw' => 'Glasgow',
  'tfx' => 'Great Falls',
  'msx' => 'Missoula'
  ),
'Nebraska' => array(
  'uex' => 'Hastings',
  'lnx' => 'North Platte',
  'oax' => 'Omaha'
  ),
'Nevada' => array(
  'lrx' => 'Elko',
  'esx' => 'Las Vegas',
  'rgx' => 'Reno'
  ),
'New Jersey' => array(
  'dix' => 'Mt. Holly'
  ),
'New Mexico' => array(
  'abx' => 'Albuquerque',
  'fdx' => 'Cannon AFB',
  'hdx' => 'Holloman AFB'
  ),
'New York' => array(
  'enx' => 'Albany',
  'bgm' => 'Binghamton',
  'buf' => 'Buffalo',
  'tyx' => 'Montague',
  'okx' => 'New York City',
  'okx' => 'Upton'
  ),
'North Carolina' => array(
  'rax' => 'Durham',
  'mhx' => 'Morehead City',
  'rax' => 'Raleigh',
  'ltx' => 'Wilmington'
  ),
'North Dakota' => array(
  'bis' => 'Bismarck',
  'mvx' => 'Grand Forks',
  'mbx' => 'Minot AFB'
  ),
'Ohio' => array(
  'iln' => 'Cincinnati',
  'cle' => 'Cleveland',
  'iln' => 'Dayton',
  'iln' => 'Wilmington'
  ),
'Oklahoma' => array(
  'fdr' => 'Frederick',
  'tlx' => 'Oklahoma City',
  'inx' => 'Tulsa',
  'vnx' => 'Vance AFB'
  ),
'Oregon' => array(
  'max' => 'Medford',
  'pdt' => 'Pendleton',
  'rtx' => 'Portland'
  ),
'Pennsylvania' => array(
  'dix' => 'Philadelphia',
  'pbz' => 'Pittsburgh',
  'ccx' => 'State College'
  ),
'Puerto Rico' => array(
  'jua' => 'Puerto Rico/V.I.'
  ),
'South Carolina' => array(
  'clx' => 'Charleston',
  'cae' => 'Columbia',
  'gsp' => 'Greenville',
  'gsp' => 'Spartanburg',
  'gsp' => 'Greer'
  ),
'South Dakota' => array(
  'abr' => 'Aberdeen',
  'udx' => 'Rapid City',
  'fsd' => 'Sioux falls'
  ),
'Tennessee' => array(
  'mrx' => 'Knoxville',
  'nqa' => 'Memphis',
  'mrx' => 'Morristown',
  'ohx' => 'Nashville',
  'mrx' => 'Tri Cities'
  ),
'Texas' => array(
  'ama' => 'Amarillo',
  'ewx' => 'Austin',
  'bro' => 'Brownsville',
  'grk' => 'Central Texas',
  'crp' => 'Corpus Christi',
  'fws' => 'Dallas',
  'dyx' => 'Dyess AFB',
  'epz' => 'El Paso',
  'fws' => 'Fort Worth',
  'hgx' => 'Galveston',
  'hgx' => 'Houston',
  'dfx' => 'Laughlin AFB',
  'lbb' => 'Lubbock',
  'maf' => 'Midland/Odessa',
  'sjt' => 'San Angelo',
  'ewx' => 'San Antonio'
  ),
'Utah' => array(
  'icx' => 'Cedar City',
  'mtx' => 'Salt Lake City'
  ),
'Vermont' => array(
  'cxx' => 'Burlington'
  ),
'Virginia' => array(
  'fcx' => 'Blacksburg',
  'akq' => 'Norfolk',
  'akq' => 'Richmond',
  'fcx' => 'Roanoke',
  'lwx' => 'Sterling',
  'akq' => 'Wakefield'
  ),
'Washington' => array(
  'atx' => 'Seattle',
  'otx' => 'Spokane',
  'atx' => 'Tacoma'
  ),
'Washington DC' => array(
  'lwx' => 'Washington'
  ),
'West Virginia' => array(
  'rlx' => 'Charleston'
  ),
'Wisconsin' => array(
  'grb' => 'Green Bay',
  'arx' => 'La Crosse',
  'mkx' => 'Milwaukee'
  ),
'Wyoming' => array(
  'cys' => 'Cheyenne',
  'riw' => 'Riverton'
  )
);

?>